
spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elmboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a1b2c3

  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

  # 文件上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  # springboot2.6.3的默认mvc路径改动了
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  production: false
  basic:
    enable: false
    username: tomcat
    password: tomcat
jasypt.encryptor.password: huqw+-327s#4$,,

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
#    org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 文件上传路径，改成自己的
file:
  uploadFolder: C:/test/


# 打印sql，仅限开发环境
logging:
  level:
    com.example.elmboot.mapper.*: debug

pagehelper:
  supportMethodsArguments: true
  # helperDialect：指定分页插件使用哪种方言
  helperDialect: mysql
  # reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # page-size-zero：默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  page-size-zero: true